apiVersion: v1
kind: Secret
metadata:
  name: affiliate-secrets
  namespace: affiliate-prod
  labels:
    app.kubernetes.io/name: affiliate-platform
    app.kubernetes.io/part-of: affiliate-platform
type: Opaque
stringData:
  DB_PASSWORD: "ProdStrongPostgresPassword#2026"
  REDIS_PASSWORD: "ProdStrongRedisPassword#2026"
  APP_JWT_SECRET: "c2VjdXJlLXByb2R1Y3Rpb24tZmluYW5jaWFsLWdyYWRlLWFmZmlsaWF0ZS1qd3QtdG9rZW4tc2VjcmV0LW11c3QtYmUtNjQtYnl0ZXM="
